# Generated by Django 5.1.2 on 2024-10-17 16:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('bucket', models.IntegerField(choices=[(1, '1 day'), (2, '2 day'), (3, '3 day'), (4, '4 day'), (5, '5 day')], default=1)),
                ('next_review_at', models.DateTimeField(default=datetime.datetime(2024, 10, 17, 16, 29, 52, 910208, tzinfo=datetime.timezone.utc))),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.deck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
